version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_USER: exampleuser
      POSTGRES_DB: mydb